In [1]:
import torch
from torch import nn

# 인공신경망 만들기

In [3]:
x = torch.tensor([1.])
model = nn.Linear(1,1) # 입력 node 한 개, 출력 node 한 개인 layer 만든다

print(model.weight) # 만들면서 initilaize 해준다
print(model.bias)
print()

y = model(x)
print(y)

Parameter containing:
tensor([[0.5586]], requires_grad=True)
Parameter containing:
tensor([-0.9019], requires_grad=True)

tensor([-0.3434], grad_fn=<AddBackward0>)


실제 수식으로 비교해보자

In [4]:
y = x @ model.weight + model.bias
print(y)

tensor([-0.3434], grad_fn=<AddBackward0>)


동일한 값인 것을 볼 수 있다

In [7]:
x = torch.tensor([1.])

fc1 = nn.Linear(1,3) # input : 1, output : 3인 node로 구성 = fully-connected
fc2 = nn.Linear(3,1)

print("----- fc1 -----")
print(fc1.weight)
print(fc1.bias)
print("----- fc2 -----")
print(fc2.weight)
print(fc2.bias)
print()

x1 = fc1(x)
x2 = fc2(x1)
print(x1)
print(x2)

----- fc1 -----
Parameter containing:
tensor([[-0.3988],
        [ 0.1842],
        [-0.1550]], requires_grad=True)
Parameter containing:
tensor([-0.1147,  0.6470,  0.3014], requires_grad=True)
----- fc2 -----
Parameter containing:
tensor([[-0.1379,  0.2214,  0.0785]], requires_grad=True)
Parameter containing:
tensor([0.3519], requires_grad=True)

tensor([-0.5135,  0.8312,  0.1464], grad_fn=<AddBackward0>)
tensor([0.6183], grad_fn=<AddBackward0>)


마찬가지로 수식으로!

In [8]:
y = (x@fc1.weight + fc1.bias)@fc2.weight + fc2.bias
## (1x1 @ 1x3 + 1x3)@ 3x1 + 1x1)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x1 and 3x1)

에러가 난다 !

<img src="image/nn_linear.png" width="150">