## Pytorch Operation

Tensor
- 다차원 Arrays를 표현하는 Pytorch 클래스
- 사실상 numpy의 ndarray와 동일


## numpy to tensor

In [1]:
import numpy as np
n_array = np.arange(10).reshape(2,5)
print(n_array)
print("ndim :", n_array.ndim, "shape :", n_array.shape)

[[0 1 2 3 4]
 [5 6 7 8 9]]
ndim : 2 shape : (2, 5)


In [3]:
import torch
t_array = torch.FloatTensor(n_array)
print(t_array)
print("ndim :", t_array.ndim, "shape :", t_array.shape)

tensor([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]])
ndim : 2 shape : torch.Size([2, 5])


In [4]:
print(t_array.shape) # ?x?
print(t_array.ndim) # 차원
print(t_array.size()) # ?x?

torch.Size([2, 5])
2
torch.Size([2, 5])


### Array to Tensor

Tensor은 list나 array로도 생성 가능하다

##### Data to tensor

In [5]:
data = [[3, 5],[10, 5]]
x_data = torch.tensor(data)
x_data

tensor([[ 3,  5],
        [10,  5]])

##### ndArray to Tensor

In [6]:
nd_array_ex = np.array(data)
tensor_array = torch.from_numpy(nd_array_ex)
tensor_array

tensor([[ 3,  5],
        [10,  5]])

### numpy like operations

기본적으로 numpy operation 모두 사용 가능하다

In [28]:
data = [[3, 5, 20],[10, 5, 50], [1, 5, 10]]
x_data = torch.tensor(data)

In [8]:
x_data[1:]

tensor([[10,  5, 50],
        [ 1,  5, 10]])

In [9]:
x_data[:2, 1:]

tensor([[ 5, 20],
        [ 5, 50]])

In [10]:
x_data.flatten()

tensor([ 3,  5, 20, 10,  5, 50,  1,  5, 10])

In [12]:
torch.ones_like(x_data) # 동일한 사이즈로 1으로 채워진 tensor을 반환

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [13]:
x_data.numpy()

array([[ 3,  5, 20],
       [10,  5, 50],
       [ 1,  5, 10]])

In [14]:
x_data.shape

torch.Size([3, 3])

In [15]:
x_data.dtype

torch.int64

In [16]:
x_data.device

device(type='cpu')

In [19]:
x_data.cuda

<function Tensor.cuda>

In [29]:
torch.cuda.is_available()

False

In [26]:
if torch.cuda.is_available():
    # x_data_cuda = x_data.to('cuda') ## GPU 메모리에 올릴 경우, cuda로 해주면 GPU로 올라가게 된다
    x_data_cuda = x_data.cuda
x_data_cuda.device

NameError: name 'x_data_cuda' is not defined

### Tensor handling

view, squeeze, unsqueeze 등으로 tensor 조정 가능하다
- view : reshape와 동일하게 tensor의 shape 변환
- squeeze : 차원의 개수가 1인 차원을 삭제
- unsqueeze : 차원의 개수가 1인 차원을 추가

In [30]:
tensor_ex = torch.rand(size=(2, 3, 2))
tensor_ex

tensor([[[0.7763, 0.5336],
         [0.8395, 0.1383],
         [0.5588, 0.2901]],

        [[0.5735, 0.3975],
         [0.7096, 0.9905],
         [0.6353, 0.2335]]])

In [31]:
tensor_ex.view([-1, 6]) ## reshape와 동일하지만, 메모리가 연속적으로 되어있는 거를 변형시키지 않고 그대로 쓰는 것

tensor([[0.7763, 0.5336, 0.8395, 0.1383, 0.5588, 0.2901],
        [0.5735, 0.3975, 0.7096, 0.9905, 0.6353, 0.2335]])

In [32]:
tensor_ex.contiguous() # 연속성 확인 -> reshape의 경우는 강제로 contiguous하게 새롭게 변형한다

tensor([[[0.7763, 0.5336],
         [0.8395, 0.1383],
         [0.5588, 0.2901]],

        [[0.5735, 0.3975],
         [0.7096, 0.9905],
         [0.6353, 0.2335]]])

view vs reshap
- contiguous 속성을 만족하지 않는 텐서에게 적용이 가능한지 여부에 따라 달라진다

|view|reshap|
|:--:|:--:|
|contiguous 속성이 만족되지 않는 경우 일부 사용이 제한될 수 있다|contiguous 속성이 만족되지 않아도 사용 가능!|

*contiguous
-  자료를 저장할 때, 행 기준 오른쪽 방향으로 순서대로 저장되는 경우 = contiguous = True 상태
- 자료 저장 순서가 원래 방향과 어긋난 경우 (열 순서대로 저장되는 등) = contiguous = False 상태

메소드
- stride() : 데이터의 저장 방향을 조회할 수 있다
- contiguous() : contiguous = True 상태로 변경해주는 것
- is_contiguous() : contiguous = True 여부 파악

https://jimmy-ai.tistory.com/122

In [33]:
tensor_ex.reshape([-1,6])

tensor([[0.7763, 0.5336, 0.8395, 0.1383, 0.5588, 0.2901],
        [0.5735, 0.3975, 0.7096, 0.9905, 0.6353, 0.2335]])

In [34]:
a = torch.zeros(3, 2)
b = a.view(2, 3)
a.fill_(1)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [35]:
a

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [36]:
b # a만 채워도 b도 찬 것을 볼 수 있다!

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [37]:
a = torch.zeros(3, 2)
b = a.t().reshape(6)
a.fill_(1)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [38]:
a

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [39]:
b # reshape의 경우, 복사해서 사용해 b를 채우지 않는다 = 즉, 메모리적으로 연결되어있지 않는다

tensor([0., 0., 0., 0., 0., 0.])

In [45]:
tensor_ex = torch.rand(size=(2, 1, 2))
tensor_ex.squeeze() # 차원의 개수가 1인 차원을 알아서 삭제해줌

tensor([[0.1420, 0.5545],
        [0.0621, 0.8144]])

In [49]:
tensor_ex = torch.rand(size=(2, 1, 2))
tensor_ex

tensor([[[0.8239, 0.4444]],

        [[0.4308, 0.0999]]])

In [50]:
tensor_ex.squeeze()

tensor([[0.8239, 0.4444],
        [0.4308, 0.0999]])

In [41]:
tensor_ex = torch.rand(size=(2, 2))
tensor_ex.unsqueeze(0).shape # shape(?, ?, ?) -> 중 인덱싱 번호에 따라 늘린다

torch.Size([1, 2, 2])

In [42]:
tensor_ex.unsqueeze(1).shape

torch.Size([2, 1, 2])

In [43]:
tensor_ex.unsqueeze(2).shape

torch.Size([2, 2, 1])

## tensor operations

In [51]:
n1 = np.arange(10).reshape(2,5)
n2 = np.arange(10).reshape(5,2)
t1 = torch.FloatTensor(n1)
t2 = torch.FloatTensor(n2)

t1 + t1 # 브로드캐스팅 자동으로 됨

tensor([[ 0.,  2.,  4.,  6.,  8.],
        [10., 12., 14., 16., 18.]])

In [52]:
t1 - t1

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [53]:
t1 + 10

tensor([[10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.]])

In [54]:
t1 + t2

RuntimeError: The size of tensor a (5) must match the size of tensor b (2) at non-singleton dimension 1

In [59]:
n2 = np.arange(10).reshape(5,2)
t2 = torch.FloatTensor(n2)

t1.mm(t2)

tensor([[ 60.,  70.],
        [160., 195.]])

In [57]:
t1.dot(t2) # 벡터의 내적만 지원, 행렬의 연산은 지원 X

RuntimeError: 1D tensors expected, but got 2D and 2D tensors

|dot|matmul|mm|bmm|
|:--:|:--:|:--:|:--:|
|벡터의 내적 지원|벡터의 내적, 행렬의 연산 모두 지원|행렬의 곱셈, broadcasting을 지원 X, batch 차원 연산 지원 X, 2차원 행렬의 곱 연산만 지원|3차원 텐서의 곱 연산|
||데이터의 크기를 모르는 경우 사용|[n, m] x [m,p] = [n,p]|[B, n, m] x [B, m, p] = [B, n, p]|

In [58]:
t1.matmul(t2)

tensor([[ 60.,  70.],
        [160., 195.]])

In [60]:
a = torch.rand(10)
b = torch.rand(10)
a.dot(b)

tensor(1.7514)

In [62]:
a = torch.rand(10)
b = torch.rand(10)
a.mm(b) # 벡터끼리는 연산 진행 X

RuntimeError: self must be a matrix

In [64]:
a = torch.rand(5,2, 3)
b = torch.rand(5)
a.mm(b) # 크기가 달라 안된다

RuntimeError: self must be a matrix

In [65]:
a = torch.rand(5,2, 3)
b = torch.rand(3)
a.matmul(b) # 브로드캐스팅이 일어나 가능하다

tensor([[0.5965, 0.7184],
        [1.1618, 0.9454],
        [0.8972, 0.4959],
        [0.4746, 0.7891],
        [0.6460, 0.5066]])

In [66]:
a[0].mm(torch.unsqueeze(b,1)).squeeze()

tensor([0.5965, 0.7184])

## tensor operations for ML/DL formula

In [67]:
import torch
import torch.nn.functional as F

tensor = torch.FloatTensor([0.5, 0.7, 0.1])
h_tensor = F.softmax(tensor, dim=0) # 해당 3개의 값을 1로 정규화 시킨 후, 그 값의 비율만큼 나오게끔 함
h_tensor


tensor([0.3458, 0.4224, 0.2318])

In [71]:
y = torch.randint(5, (10,5))
print(y)
y_label = y.argmax(dim=1) # 가장 큰 값을 찾아주는 것
print(y_label)

tensor([[0, 3, 1, 3, 1],
        [4, 0, 4, 2, 0],
        [3, 0, 2, 1, 1],
        [4, 3, 2, 2, 2],
        [1, 1, 4, 4, 0],
        [3, 1, 4, 3, 4],
        [3, 4, 4, 1, 1],
        [3, 4, 4, 1, 1],
        [2, 0, 4, 0, 0],
        [3, 4, 1, 4, 3]])
tensor([1, 0, 0, 0, 2, 2, 1, 1, 2, 1])


In [72]:
torch.nn.functional.one_hot(y_label) # 가장 큰 값을 1로 만들어준 것

tensor([[0, 1, 0],
        [1, 0, 0],
        [1, 0, 0],
        [1, 0, 0],
        [0, 0, 1],
        [0, 0, 1],
        [0, 1, 0],
        [0, 1, 0],
        [0, 0, 1],
        [0, 1, 0]])

In [73]:
import itertools
a = [1, 2, 3]
b = [4, 5]
list(itertools.product(a, b))
## itertools.product(a, b) : 두개 이상의 리스트(or 집합) 끼리의 데카르트 곱(cartesian product)를 계산하여 iterator로 반환
## * 데카르트 곱(cartesian product) : 각 집합에 속한 원소들의 합 쌍을 출력하는 것

[(1, 4), (1, 5), (2, 4), (2, 5), (3, 4), (3, 5)]

In [74]:
tensor_a = torch.tensor(a)
tensor_b = torch.tensor(b)
torch.cartesian_prod(tensor_a, tensor_b)

tensor([[1, 4],
        [1, 5],
        [2, 4],
        [2, 5],
        [3, 4],
        [3, 5]])

## torch autogard

Pytorch의 핵심은 자동 미분의 지원! -> backward 함수를 사용

$$
y = w^2 \\ 
z = 10*y + 25 \\
z = 10*w^2 + 25 
$$

In [75]:
w = torch.tensor(2.0, requires_grad=True)
y = w**2
z = 10*y + 50
z.backward()
w.grad # z에 대해 w 미분값을 출력하는 것

## y = 2w
## z = 20w = 20 * 2.0 = 40

tensor(40.)

$$ Q = 3a^3 - b^2  $$

In [76]:
a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)
Q = 3*a**3 - b**2
external_grad = torch.tensor([1., 1.])
Q.backward(gradient=external_grad)

a.grad 

tensor([36., 81.])

In [77]:
b.grad

tensor([-12.,  -8.])

$$ \frac{\partial Q}{\partial a} = 9a^2 $$  

$$ \frac{\partial Q}{\partial b} = -2b $$