# Pytorch Basic

In [1]:
import torch
import numpy as np

## Tensor Basic

In [2]:
a = torch.tensor([1,2,3,4])
a_np = np.array([1,2,3,4])

print(a)
print(a_np)
print("\n")

print(f"type : {type(a)}")
print(f"data type : {a.dtype}")
print(f"shape : {a.shape}") # == a.size()

tensor([1, 2, 3, 4])
[1 2 3 4]


type : <class 'torch.Tensor'>
data type : torch.int64
shape : torch.Size([4])


In [3]:
b = torch.tensor([1,2,3.1    ,4])
print(b.dtype) # 실수가 하나라도 들어갈 경우, 자동으로 실수 타입으로 변환
print(b) # 다른 int 또한 실수 타입으로 변환

torch.float32
tensor([1.0000, 2.0000, 3.1000, 4.0000])


In [4]:
A = torch.tensor([[1,2], [3,4]])
print(A)
### 행렬이기 때문에 각 행에 해당하는 숫자의 개수 일치 필요
# A = torch.tensor([[1,2], [3,4, 5, 6]])
print("\n")

print(f"shape : {A.shape}") # 2x2
print(f"차원 수 : {A.ndim}") # 2차원
print(f"전체 성분 수 : {A.numel()}") # = np.size

tensor([[1, 2],
        [3, 4]])


shape : torch.Size([2, 2])
차원 수 : 2
전체 성분 수 : 4


In [5]:
A = torch.tensor([ [[1,2,3],[4,5,6],[7,8,9]],
                  [[10,11,12],[14,15,16],[17,18,19]]])
print(A)
print(f"A shape : {A.shape}")

a = torch.tensor([[[1,2,3,4]]])
print(f"a shape : {a.shape}")

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [14, 15, 16],
         [17, 18, 19]]])
A shape : torch.Size([2, 3, 3])
a shape : torch.Size([1, 1, 4])


- shape 표기법 : 채널 개수, 행, 열
- [] (차원) 가 하나씩 추가될 때마다, 이에 대한 개수가 왼쪽부터 추가가 된다

- 만약 4차원일 경우, >> 개수, 개수, 행, 열

In [8]:
A = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(A)
print(f"A shape : {A.shape}")

A = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
print(A)
print(f"a shape : {A.shape}")

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
A shape : torch.Size([3, 3])
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
a shape : torch.Size([1, 3, 3])


In [8]:
print(torch.zeros(5)) # 5개의 zeors tensor
print(torch.zeros_like(A)) # A와 동일한 shape의 zeros
print(torch.zeros(3,3)) # 3x3 tensor zero로 생성
# print(torch.zeros( (3,3)) ) # 튜플을 입력으로 넣어도 된다
print("\n")

print(torch.ones(5)) # 5개의 ones tensor
print("\n")

print(torch.arange(3,10,2)) # range랑 동일하게 tensor 만듦
print(torch.arange(0,1,0.1)) # 소수점도 가능
print("\n")

print(torch.linspace(0,1,10)) # 시작점 : 0, 끝 점 : 1, 개수 : 10개로 간격 맞춰 생성
print(torch.linspace(0,2,10)) # 시작점 : 0, 끝 점 : 2, 개수 : 10개로 간격 맞춰 생성

tensor([0., 0., 0., 0., 0.])
tensor([[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


tensor([1., 1., 1., 1., 1.])


tensor([3, 5, 7, 9])
tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000,
        0.9000])


tensor([0.0000, 0.1111, 0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.7778, 0.8889,
        1.0000])
tensor([0.0000, 0.2222, 0.4444, 0.6667, 0.8889, 1.1111, 1.3333, 1.5556, 1.7778,
        2.0000])


arange vs linxpace

- arange : (x,y,z) 중 z 간격을 기준으로 생성
- linxpace : (x,y,z) 중 z개를 생성

## Tensor간의 연산

In [9]:
a = torch.tensor([1,2,3,4])
b = torch.tensor([5,6,7,8])
print(a+b)
print("\n")

A = torch.tensor([[1,2], [1,2]])
B = torch.tensor([[3,4], [3,4]])
print(A+B)
print(A-B)

tensor([ 6,  8, 10, 12])


tensor([[4, 6],
        [4, 6]])
tensor([[-2, -2],
        [-2, -2]])


In [10]:
print(A*B) # Hadamard Product = element-wise 곱셈
print(A/B)
print(B**2)

tensor([[3, 8],
        [3, 8]])
tensor([[0.3333, 0.5000],
        [0.3333, 0.5000]])
tensor([[ 9, 16],
        [ 9, 16]])


곱셈, 나눗셈, 제곱 > 각 성분에 대해서 해준다

- Hadamard 계산이기 때문에 동일한 shape를 가진 tensor에 적용

In [11]:
print(A@B) # 내적 = dot product

tensor([[ 9, 12],
        [ 9, 12]])


|                              Hadamard Product                               | 내적 |
| :----------------------------------------------------------------: | :----------: |
|각 원소별로 곱셈값|일반적인 행렬 곱셈|
|= element-wise 곱셈|= dot product|

행렬곱셈

- (x,y)@(a,b) > y = a가 맞아야 성립

# Tensor 인덱싱

## Boolean으로 인덱싱

In [12]:
a = [1,2,3,5,4,6,3,3]
print(a==3) # 리스트 =/= 3이므로, False
print("\n")

A = torch.tensor([[1,2,3,4],[5,3,7,3]])
print(A==3) # 각 성분에 대해 해당 값과 동일한지 비교해주게 된다
print(A[A==3]) # 성분가 3과 동일한 값들로 인덱싱

False


tensor([[False, False,  True, False],
        [False,  True, False,  True]])
tensor([3, 3, 3])


In [21]:
A=torch.tensor([[1,2],[3,4],[5,6],[7,8]])
B=torch.tensor([True,False,False,True]) # 그냥 리스트여도 가능하다! tensor type 맞춰줄 필요 없다
print(A[B,:])
# 행 자리에 boolean tensor를 넣어주어 해당 boolean에 따라서 True인 행에 대해서 출력

b=torch.tensor([1,2,3,4]) # 4
print(b[[True,False,True,True]])
print(b.shape)

tensor([[1, 2],
        [7, 8]])
tensor([1, 3, 4])
torch.Size([4])


In [20]:
c=[1,2,3,4]
c[[True,False,False,True]]

TypeError: list indices must be integers or slices, not list

- tensor은 가능하지만, list는 불가능하다

## Tensor로 인덱싱

In [15]:
a=torch.tensor([1,2,3,4,5])
print(a[2])
print( a[torch.tensor(2)] ) # tensor로도 접근 가능
print()
print( a[torch.tensor([2,3,4])] )
print( a[torch.tensor([[2,2,2],[3,3,3]])] )
# 각 인덱싱에 부합하는 값으로, tensor shape에 맞춰 tensor 반환!

tensor(3)
tensor(3)

tensor([3, 4, 5])
tensor([[3, 3, 3],
        [4, 4, 4]])


In [29]:
a=torch.tensor([[1,2,3],[4,5,6]])
print(a)

print( a[torch.tensor([[0,1],[1,1]])] )
# a[0] = [1,2,3] 이므로, 앞과 마찬가지로 인덱싱 값에 따라 각 위치에 맞게 tensor 반환
print( a[torch.tensor([[0,1],[1,1]])].shape )

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[4, 5, 6],
         [4, 5, 6]]])
torch.Size([2, 2, 3])


segmentation 결과 그림 보여줄 때, tensor 인덱싱을 활용!
- 만약 고양이 그림 (5)을 주황색으로 칠한다고 하자
- 해당 5번째 인덱스를 가진 그림에 대해 3개의 값인 RGB값을 부여해야 하므로, 이때 활용한다

## 인덱싱 종류 정리

In [17]:
A = torch.Tensor([[1,2],[3,4],[5,6],[7,8]])

# 1.
print(A[0,1])
print()
# 2.
print(A[ torch.tensor([[False,True],[False,False],[True,True],[False,True]]) ])
print(A[A==2])
print()
# 3.
print(A[ [True,False,False,False],[False,True] ])
print()
# 4.
print(A[ torch.tensor([1,2,2,1,2]) ])

tensor(2.)

tensor([2., 5., 6., 8.])
tensor([2.])

tensor([2.])

tensor([[3., 4.],
        [5., 6.],
        [5., 6.],
        [3., 4.],
        [5., 6.]])


In [18]:
A = torch.Tensor([[1,2,9],[5,6,9],[7,8,9]])
print(A.shape)

# 2.
print(A[ torch.tensor([[False,True,True],[True,True,True],[False,False,True]]) ])
# 3.
print(A[ [True,False,False],[False,True,True] ])

torch.Size([3, 3])
tensor([2., 9., 5., 6., 9., 9.])
tensor([2., 9.])


2번
- 2와 같은 경우에는, A와 shape를 맞춰주어 동일한 인덱스를 가진 값이 True일 때만 출력하는 것
<img src="image/boolean_indexing3.jpeg" width="300">

3번
- 3과 같은 경우, A shape 수와 일치하는 행렬을 통해 각 행과 열이 True인지 부여하는 것
<img src="image/boolean_indexing1.jpeg" width="300">

# Pytorch의 여러 함수들

In [19]:
A=torch.rand(3,3) # 0과 1 사이의 uniform 분포에서 랜덤 샘플링
print(A)
print()
B=torch.randn(3,3) # 평균 : 0, 분산 : 1인 정규분포에서 랜덤 샘플링
print(B)

tensor([[0.9811, 0.9538, 0.6762],
        [0.9342, 0.8575, 0.1080],
        [0.2240, 0.7824, 0.7007]])

tensor([[-0.9383,  0.7463, -0.3835],
        [ 1.7961,  0.7976,  0.4311],
        [ 0.5847,  0.7438, -0.1169]])


In [31]:
A=torch.randn(3,3)
print(A)
print()

print(torch.abs(A)) # 절대값
print(torch.sqrt(torch.abs(A))) # square root
print(torch.exp(A)) # e^A
# 각 값에 대해 e^a11 e^a21 e^a31 ... 한 행렬 값이 나온다
# torch.exp(1) > 이와 같이 int를 넣으면, 에러! tensor로 넣어줘야 한다
  # => torch.exp(torch.tensor(1))
print()

print(torch.log(torch.abs(A))) # 밑이 e인 log
print(torch.log10(torch.tensor(10))) # 밑이 10인 log
print(torch.log2(torch.tensor(2))) # 밑이 2인 log
# 함수로 정의된 것이다! log3 처럼 밑 변경하는 것 아님

tensor([[ 0.6403, -0.4638,  0.7515],
        [-2.6443,  1.1417, -0.5035],
        [-0.8537,  0.0849,  0.1644]])

tensor([[0.6403, 0.4638, 0.7515],
        [2.6443, 1.1417, 0.5035],
        [0.8537, 0.0849, 0.1644]])
tensor([[0.8002, 0.6810, 0.8669],
        [1.6261, 1.0685, 0.7096],
        [0.9240, 0.2914, 0.4054]])
tensor([[1.8970, 0.6289, 2.1201],
        [0.0711, 3.1321, 0.6044],
        [0.4258, 1.0886, 1.1787]])

tensor([[-0.4459, -0.7683, -0.2858],
        [ 0.9724,  0.1325, -0.6861],
        [-0.1581, -2.4661, -1.8055]])
tensor(1.)
tensor(1.)


In [34]:
print(torch.round(A))
print(torch.round(A, decimals=2))
# np에서는 그냥 적어도 상관 없었지만, torch에서는 decimals를 적어줘야 한다
print()

print(torch.floor(A)) # 내림
print(torch.ceil(A)) # 올림

tensor([[ 1., -0.,  1.],
        [-3.,  1., -1.],
        [-1.,  0.,  0.]])
tensor([[ 0.6400, -0.4600,  0.7500],
        [-2.6400,  1.1400, -0.5000],
        [-0.8500,  0.0800,  0.1600]])

tensor([[ 0., -1.,  0.],
        [-3.,  1., -1.],
        [-1.,  0.,  0.]])
tensor([[ 1., -0.,  1.],
        [-2.,  2., -0.],
        [-0.,  1.,  1.]])


In [22]:
print(torch.sin(torch.tensor(torch.pi/6)))
# type(torch.pi)자체는 float이기 때문에 tensor로 변환해서 sin 함수 안에 넣어줘야 한다
# torch.Tensor(3.14/6)의 type은 tensor로 나오므로, tensor로 변환 안해줘도 됨!
print(torch.cos(torch.tensor(torch.pi/3)))
print(torch.tan(torch.tensor(torch.pi/4)))
print(torch.tanh(torch.tensor(-10)))

tensor(0.5000)
tensor(0.5000)
tensor(1.)
tensor(-1.)


In [23]:
torch.nan # not a number
print(torch.log(torch.tensor(-1))) # 숫자가 아니기 때문에 nan으로 출력
print()
print(torch.isnan(torch.tensor([1,2,torch.nan,3,4])))
# 각 성분에 대해 nan인지 boolean으로 출력하는 것

torch.inf # 무한대
print(torch.isinf(torch.tensor([1,2,torch.inf,3,4])))

tensor(nan)

tensor([False, False,  True, False, False])
tensor([False, False,  True, False, False])


In [24]:
A=torch.randn(3,4)
print(A)
print()
print(torch.max(A))
print(torch.max(A,dim=1)) # axis도 동작하긴 한다
  # dim=1 행, dim=0 열
# 1번째 dimension이니까, 3개의 행 값 중에서 가장 큰 것 출력
# dim을 사용하면, 각 행/열 중 가장 큰 값에 대한 인덱스도 함게 출력
print(torch.max(A,dim=1, keepdims=True))
# keepdims: input과 동일한 shape로 출력
  # max의 경우, (3)으로 변하지만 keepdims은 (3,1)으로 맞춰서 나온다

tensor([[ 0.3372,  3.8510, -0.0975,  1.6552],
        [-0.8190,  1.5040,  0.1118,  0.5201],
        [-2.1515, -0.1471, -0.0946, -1.2219]])

tensor(3.8510)
torch.return_types.max(
values=tensor([ 3.8510,  1.5040, -0.0946]),
indices=tensor([1, 1, 2]))
torch.return_types.max(
values=tensor([[ 3.8510],
        [ 1.5040],
        [-0.0946]]),
indices=tensor([[1],
        [1],
        [2]]))


In [38]:
print(torch.min(A))
print(torch.min(A,dim=0))
print()
print(A)
print(torch.argmax(A))
print(torch.argmax(A,dim=0))

tensor(-2.6443)
torch.return_types.min(
values=tensor([-2.6443, -0.4638, -0.5035]),
indices=tensor([1, 0, 1]))

tensor([[ 0.6403, -0.4638,  0.7515],
        [-2.6443,  1.1417, -0.5035],
        [-0.8537,  0.0849,  0.1644]])
tensor(4)
tensor([0, 1, 0])


max vs argmax
- max : 함수 값 (y) 중 제일 큰 값
- argmax : 제일 큰 값인 y를 가질 때의 x 값

=> 즉, max 함수와 dim이 동일할 경우, 나오는 index값이 동일하다
- 다만 max는 값과 인덱스, 함께 나오며 argmax는 인덱스만 출력해주는 것

sum, mean, std도 있다!

In [26]:
a=torch.randn(6,1)
print(a)
print(torch.sort(a,dim=0))
# 기본적으로 dim=1에 대해 sort하기 때문에, 꼭 dim를 남겨야 한다 !
# 오름차순 기본 만약 내림차순을 원한다면 descending=True 추가
# = a.sort() 또한 가능

tensor([[ 1.3419],
        [-1.4605],
        [ 0.3285],
        [-0.0048],
        [-0.4916],
        [-0.9996]])
torch.return_types.sort(
values=tensor([[-1.4605],
        [-0.9996],
        [-0.4916],
        [-0.0048],
        [ 0.3285],
        [ 1.3419]]),
indices=tensor([[1],
        [5],
        [4],
        [3],
        [2],
        [0]]))


sort와 같이 max, abs 또한 tensor에 직접 접근하는 것이 아닌 클래스내의 메소드로 접근 가능!
- max(), abs()

In [48]:
a=torch.randn(6,2)

print(a)
print(a.transpose(1,0))
print(a.transpose(1,0).shape)
print()
print(a.permute(1,0)) # 3차원 이상부터!
print(a.T) # 정 transpose
# = a.t()@b
print()

tensor([[ 0.3432,  0.0192],
        [-1.1015,  0.1584],
        [ 0.6346,  3.5619],
        [ 0.3559, -0.0965],
        [ 1.5236,  0.1649],
        [-2.1803, -0.1062]])
tensor([[ 0.3432, -1.1015,  0.6346,  0.3559,  1.5236, -2.1803],
        [ 0.0192,  0.1584,  3.5619, -0.0965,  0.1649, -0.1062]])
torch.Size([2, 6])

tensor([[ 0.3432, -1.1015,  0.6346,  0.3559,  1.5236, -2.1803],
        [ 0.0192,  0.1584,  3.5619, -0.0965,  0.1649, -0.1062]])
tensor([[ 0.3432, -1.1015,  0.6346,  0.3559,  1.5236, -2.1803],
        [ 0.0192,  0.1584,  3.5619, -0.0965,  0.1649, -0.1062]])



In [58]:
A=torch.randn(4,3,6)
print(A.permute(0,2,1))
print(A.permute(0,2,1).shape)
# 0번째에 0번째, 1번째에 2번째, 3번째엔 1번째
print(A.transpose(2,1).shape) # transpose는 두개만 자리 바꿀 수 있음

tensor([[[ 0.9359, -0.3400,  0.1906],
         [-1.3374, -1.2386,  0.3413],
         [-0.3114,  0.8615, -0.7548],
         [-0.6752, -1.7877, -2.3720],
         [ 0.7999,  1.1923,  0.6779],
         [ 1.9540,  0.2970,  1.3421]],

        [[ 0.1849,  1.3251,  0.5701],
         [-1.2081,  0.7018,  1.0157],
         [-0.8808, -1.0474,  1.8949],
         [ 0.0247,  1.4308,  1.0180],
         [ 2.0461, -0.8170,  1.3961],
         [-0.5640,  0.4605,  0.0742]],

        [[-0.1733, -0.1363,  0.1631],
         [-0.9583, -0.3553,  0.7722],
         [ 2.3356, -0.6815, -2.2323],
         [-0.7312,  1.8947, -0.4968],
         [-0.5564,  0.8773,  0.4471],
         [-1.9082,  0.0905,  0.6545]],

        [[-0.3368,  1.0990,  0.1841],
         [-0.7049, -0.8579,  0.1795],
         [ 0.8643,  1.1305,  0.0949],
         [ 0.7231,  0.3684, -1.2087],
         [ 0.3952,  1.2895, -0.5697],
         [ 0.7637,  1.6949, -1.1531]]])
torch.Size([4, 6, 3])
torch.Size([4, 6, 3])


In [28]:
A=torch.randint(1,5,size=(12,))
# 1부터 5미만 12개 정수 랜덤하게 추출
  # 1 차원은 (N,)
print(A)
print(A.shape)

B=A.reshape(2,2,3) # 2행 3열짜리 2개로 shape을 바꿔달라!
  # 12개면 3으로 먼저 끊고 > 3개짜리를 2개로 묶고 > 이를 2개로 만든다
  # 이처럼 뒤에서부터 수행하기 때문에 동일한 shape를 가졌더라도 다른 값이 들어갈 수 있으니 유의!
print(B)
print(B.ndim) # 3차원 행렬

tensor([3, 2, 4, 3, 4, 3, 3, 3, 2, 3, 2, 3])
torch.Size([12])
tensor([[[3, 2, 4],
         [3, 4, 3]],

        [[3, 3, 2],
         [3, 2, 3]]])
3


In [29]:
A=torch.arange(20)
print(A)
print(A.reshape(4,5))
print(A.reshape(4,-1).shape) # 앞 행을 참고해서 알아서 열의 수를 맞춰주는 것
print()

# 행 벡터, 열 벡터를 만들 때 다음과 같이 많이 사용한다!
print(A.reshape(1,-1).shape) # 행 벡터
print(A.reshape(-1,1).shape) # 2차원 열 벡터

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])
tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])
torch.Size([4, 5])

torch.Size([1, 20])
torch.Size([20, 1])


In [59]:
x=torch.randn(2,3,4,5,6)
print(x[1,2,:,:,:].shape)
print(x[1,2,...].shape) # = x[1, 2, :, :, :]과 동일
print(x[:,:,:,:,3].shape)
print(x[...,3].shape) # = x[:, :, :, :, 3]과 동일
print(x[1,:,:,3,:].shape)
print(x[1,...,3,:].shape) # = x[1, :, :, 3, :]과 동일
# :,를 ...로 대체해서 사용 가능

torch.Size([4, 5, 6])
torch.Size([4, 5, 6])
torch.Size([2, 3, 4, 5])
torch.Size([2, 3, 4, 5])
torch.Size([3, 4, 6])
torch.Size([3, 4, 5])


In [31]:
A=torch.ones((3,2))
B=torch.zeros((3,2))

C=torch.vstack([A,B])
D=torch.hstack([A,B]) # v는 0번째 차원, h는 1번째 차원에 쌓는다.

print(C)
print(C.shape)
print(D)
print(D.shape)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])
torch.Size([6, 2])
tensor([[1., 1., 0., 0.],
        [1., 1., 0., 0.],
        [1., 1., 0., 0.]])
torch.Size([3, 4])


In [64]:
A=torch.ones((2,3,4))
B=torch.zeros((2,3,4))

# = numpy block = concatenation
  # 각 dim을 기준으로 추가한다
E=torch.cat([A,B], dim=0)
print(E.shape)
F=torch.cat([A,B], dim=1)
print(F.shape)
G=torch.cat([A,B], dim=2)
print(G.shape)

torch.Size([4, 3, 4])
torch.Size([2, 6, 4])
torch.Size([2, 3, 8])


In [67]:
A = torch.randn(1,1,1,3,1,1,4,1)
print(A)
print()
print(A.shape)
print(A.squeeze().shape)
# 해당 tensor에서 shape 1은 의미가 없으니까 squeeze로 1인 차원을 제거해주는 것
  # input data 차원에 맞춰야하는 경우, 사용 가능하다!
# 보통 인덱스 부여해서 해준다 > 0이나 -1 처럼 가장 바깥 거나 안쪽거는 쓸모없으니까 제거해주는 용도

tensor([[[[[[[[-0.8151],
              [ 1.6244],
              [ 1.1603],
              [ 1.0319]]]],



           [[[[-1.6093],
              [-0.4293],
              [ 1.2591],
              [-0.4259]]]],



           [[[[ 0.4049],
              [-0.0873],
              [ 1.0041],
              [-0.5879]]]]]]]])

torch.Size([1, 1, 1, 3, 1, 1, 4, 1])
torch.Size([3, 4])


In [34]:
A = torch.randn(3,4)
print(A.unsqueeze(dim=0).shape) # 1인 차원을 추가해주는 것!
# = A.reshape(1,3,4), shape도 동일하고 내부 값들도 모두 동일하다!
print(A.unsqueeze(dim=1).shape) # = A.reshape(3,1,4)
print(A.unsqueeze(dim=2).shape) # = A.reshape(3,4,1)

torch.Size([1, 3, 4])
torch.Size([3, 1, 4])
torch.Size([3, 4, 1])


In [35]:
# unsqueeze 예시!
A=torch.ones(3,4)
B=torch.zeros(3,4)
# 해당 3x4 tensor를 가지고, 겹쳐 2x3x4 (3x4 tensor, 2개 차원)을 만들고 싶다!
  # > torch.cat 등 다른 것들은 6x4 or 3x8 등 붙이는 것만 가능
A=A.unsqueeze(dim=0)
B=B.unsqueeze(dim=0) # (1,3,4)로 차원을 늘린 후
C=torch.cat([A,B], dim=0) # 붙이기
print(C)
print(C.shape)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
torch.Size([2, 3, 4])


In [36]:
A=torch.tensor([[1,2],[3,4]])
B=A.clone() # 그냥 B=A인 경우, 주소까지 같이 보내는 것
# 만약 A의 값만 사용하고 싶다면, clone 사용!
B[0,0]=100

print(B)
print(A) # A는 안 변한 것 확인 !

tensor([[100,   2],
        [  3,   4]])
tensor([[1, 2],
        [3, 4]])


In [2]:
X = torch.tensor([[[1,2],[3,4]],[[5,6],[7,8]]])
print(X)
print(torch.flatten(X, start_dim=0)) # default
print(torch.flatten(X, start_dim=1))

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
tensor([1, 2, 3, 4, 5, 6, 7, 8])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


<img src="image/flatten.jpeg" width="300">

# @ 추가 설명

In [69]:
A=torch.randn(5,7)
B=torch.randn(7,10)
C=A@B
print(C.shape) # 5x7@7x10 = 5x10

A=torch.randn(32,5,7)
B=torch.randn(32,7,10)
C=A@B # 5x7@7x10 계산을 32개에 대해 각각 계산한다
print(C.shape) # 5x10 행렬이 32차원으로 나타남

torch.Size([5, 10])
torch.Size([32, 5, 10])


In [75]:
B=torch.randn(2,5)
print(B)
print(B.repeat(3,2)) # 2x5 행렬을 3차원으로 반복해서 만든다

tensor([[-0.3088, -1.8175,  1.7420,  0.8383, -1.0566],
        [ 0.0231, -2.3690, -0.5960,  0.5770, -0.8623]])
tensor([[-0.3088, -1.8175,  1.7420,  0.8383, -1.0566, -0.3088, -1.8175,  1.7420,
          0.8383, -1.0566],
        [ 0.0231, -2.3690, -0.5960,  0.5770, -0.8623,  0.0231, -2.3690, -0.5960,
          0.5770, -0.8623],
        [-0.3088, -1.8175,  1.7420,  0.8383, -1.0566, -0.3088, -1.8175,  1.7420,
          0.8383, -1.0566],
        [ 0.0231, -2.3690, -0.5960,  0.5770, -0.8623,  0.0231, -2.3690, -0.5960,
          0.5770, -0.8623],
        [-0.3088, -1.8175,  1.7420,  0.8383, -1.0566, -0.3088, -1.8175,  1.7420,
          0.8383, -1.0566],
        [ 0.0231, -2.3690, -0.5960,  0.5770, -0.8623,  0.0231, -2.3690, -0.5960,
          0.5770, -0.8623]])


In [79]:
A=torch.randn(32,5,7)
B=torch.randn(7,10)

# shape 맞춰 계산
C=A@B.repeat(32,1,1) # B.repeat(32,1,1) = 동일한 7x10 행렬을 32개 가진 tensor B
print(C.shape)

# repeat 없이 그냥 계산 = shape 안 맞음
D=A@B
print(D.shape)

print(C == D) # 동일한 결과 값이어야 하는 거 아닌가..? 왜 다른 것도 있지?
# print((C-D).abs().max()) > 그렇게 크게 차이나지 않는다 ?

torch.Size([32, 5, 10])
torch.Size([32, 5, 10])
tensor([[[ True,  True,  True,  ...,  True,  True,  True],
         [ True,  True,  True,  ...,  True,  True,  True],
         [ True,  True,  True,  ...,  True, False,  True],
         [ True,  True,  True,  ...,  True, False,  True],
         [ True,  True,  True,  ...,  True,  True,  True]],

        [[ True,  True,  True,  ...,  True,  True,  True],
         [ True,  True,  True,  ...,  True,  True,  True],
         [ True,  True,  True,  ...,  True,  True,  True],
         [ True,  True,  True,  ...,  True, False,  True],
         [ True,  True,  True,  ...,  True,  True,  True]],

        [[ True,  True,  True,  ...,  True,  True, False],
         [ True,  True,  True,  ...,  True, False, False],
         [ True,  True,  True,  ...,  True,  True,  True],
         [ True,  True,  True,  ...,  True,  True, False],
         [ True,  True,  True,  ...,  True,  True,  True]],

        ...,

        [[ True,  True,  True,  ...,  True,  Tr

In [51]:
A=torch.randn(3,3,1)
B=torch.randn(1,2)

C=A@B.repeat(3,1,1)
print(C)

D=A@B
print(D)

print(C == D) # 얜 또 맞는다?

tensor([[[ 0.0460, -0.2198],
         [ 0.0799, -0.3820],
         [-0.0289,  0.1384]],

        [[-0.2470,  1.1811],
         [-0.0217,  0.1037],
         [-0.1246,  0.5959]],

        [[ 0.1126, -0.5382],
         [-0.0131,  0.0627],
         [-0.1261,  0.6031]]])
tensor([[[ 0.0460, -0.2198],
         [ 0.0799, -0.3820],
         [-0.0289,  0.1384]],

        [[-0.2470,  1.1811],
         [-0.0217,  0.1037],
         [-0.1246,  0.5959]],

        [[ 0.1126, -0.5382],
         [-0.0131,  0.0627],
         [-0.1261,  0.6031]]])
tensor([[[True, True],
         [True, True],
         [True, True]],

        [[True, True],
         [True, True],
         [True, True]],

        [[True, True],
         [True, True],
         [True, True]]])


In [53]:
A = torch.rand(2,3)
A_repeat=A.repeat(3,1,3,2)
print(A_repeat.shape)
print()

print(A)
print(A_repeat)

torch.Size([3, 1, 6, 6])

tensor([[0.4851, 0.0917, 0.9757],
        [0.6380, 0.3267, 0.1177]])
tensor([[[[0.4851, 0.0917, 0.9757, 0.4851, 0.0917, 0.9757],
          [0.6380, 0.3267, 0.1177, 0.6380, 0.3267, 0.1177],
          [0.4851, 0.0917, 0.9757, 0.4851, 0.0917, 0.9757],
          [0.6380, 0.3267, 0.1177, 0.6380, 0.3267, 0.1177],
          [0.4851, 0.0917, 0.9757, 0.4851, 0.0917, 0.9757],
          [0.6380, 0.3267, 0.1177, 0.6380, 0.3267, 0.1177]]],


        [[[0.4851, 0.0917, 0.9757, 0.4851, 0.0917, 0.9757],
          [0.6380, 0.3267, 0.1177, 0.6380, 0.3267, 0.1177],
          [0.4851, 0.0917, 0.9757, 0.4851, 0.0917, 0.9757],
          [0.6380, 0.3267, 0.1177, 0.6380, 0.3267, 0.1177],
          [0.4851, 0.0917, 0.9757, 0.4851, 0.0917, 0.9757],
          [0.6380, 0.3267, 0.1177, 0.6380, 0.3267, 0.1177]]],


        [[[0.4851, 0.0917, 0.9757, 0.4851, 0.0917, 0.9757],
          [0.6380, 0.3267, 0.1177, 0.6380, 0.3267, 0.1177],
          [0.4851, 0.0917, 0.9757, 0.4851, 0.0917, 0.9757

* 부연설명

<img src="image/tensor_indexing.jpeg" width="450">

# numpy와 torch 호환가능하다

In [40]:
import numpy as np
import torch

a=np.array([1,2,3])
b=torch.tensor([1,2,3])
A=torch.tensor(a) # A=torch.from_numpy(a)
B=b.numpy() # B=np.array(b)
print(type(A))
print(type(B))

<class 'torch.Tensor'>
<class 'numpy.ndarray'>
