# Pytorch Basic

In [1]:
import torch
import numpy as np

## Tensor Basic

In [12]:
a = torch.tensor([1,2,3,4])
a_np = np.array([1,2,3,4])

print(a)
print(a_np)
print("\n")

print(f"type : {type(a)}")
print(f"data type : {a.dtype}")
print(f"shape : {a.shape}") # == a.size()

tensor([1, 2, 3, 4])
[1 2 3 4]


type : <class 'torch.Tensor'>
data type : torch.int64
shape : torch.Size([4])


In [13]:
b = torch.tensor([1,2,3.1    ,4])
print(b.dtype) # 실수가 하나라도 들어갈 경우, 자동으로 실수 타입으로 변환
print(b) # 다른 int 또한 실수 타입으로 변환

torch.float32
tensor([1.0000, 2.0000, 3.1000, 4.0000])


In [20]:
A = torch.tensor([[1,2], [3,4]])
print(A)
### 행렬이기 때문에 각 행에 해당하는 숫자의 개수 일치 필요
# A = torch.tensor([[1,2], [3,4, 5, 6]])
print("\n")

print(f"shape : {A.shape}") # 2x2
print(f"차원 수 : {A.ndim}") # 2차원
print(f"전체 성분 수 : {A.numel()}") # = np.size

tensor([[1, 2],
        [3, 4]])


shape : torch.Size([2, 2])
차원 수 : 2
전체 성분 수 : 4


In [30]:
A = torch.tensor([ [[1,2,3],[4,5,6],[7,8,9]],
                  [[10,11,12],[14,15,16],[17,18,19]]])
print(A)
print(f"A shape : {A.shape}")

a = torch.tensor([[[1,2,3,4]]])
print(f"a shape : {a.shape}")

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [14, 15, 16],
         [17, 18, 19]]])
A.shape : torch.Size([2, 3, 3])
a.shape : torch.Size([1, 1, 4])


- shape 표기법 : 채널 개수, 행, 열
- [] (차원) 가 하나씩 추가될 때마다, 이에 대한 개수가 왼쪽부터 추가가 된다

- 만약 4차원일 경우, >> 개수, 개수, 행, 열

In [21]:
print(torch.zeros(5)) # 5개의 zeors tensor
print(torch.zeros_like(A)) # A와 동일한 shape의 zeros
print(torch.zeros(3,3)) # 3x3 tensor zero로 생성
# print(torch.zeros( (3,3)) ) # 튜플을 입력으로 넣어도 된다
print("\n")

print(torch.ones(5)) # 5개의 ones tensor
print("\n")

print(torch.arange(3,10,2)) # range랑 동일하게 tensor 만듦
print(torch.arange(0,1,0.1)) # 소수점도 가능
print("\n")

print(torch.linspace(0,1,10)) # 시작점 : 0, 끝 점 : 1, 개수 : 10개로 간격 맞춰 생성
print(torch.linspace(0,2,10)) # 시작점 : 0, 끝 점 : 2, 개수 : 10개로 간격 맞춰 생성

tensor([0., 0., 0., 0., 0.])
tensor([[0, 0],
        [0, 0]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


tensor([1., 1., 1., 1., 1.])


tensor([3, 5, 7, 9])
tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000,
        0.9000])


tensor([0.0000, 0.1111, 0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.7778, 0.8889,
        1.0000])
tensor([0.0000, 0.2222, 0.4444, 0.6667, 0.8889, 1.1111, 1.3333, 1.5556, 1.7778,
        2.0000])


arange vs linxpace

- arange : (x,y,z) 중 z 간격을 기준으로 생성
- linxpace : (x,y,z) 중 z개를 생성

## Tensor간의 연산

In [24]:
a = torch.tensor([1,2,3,4])
b = torch.tensor([5,6,7,8])
print(a+b)
print("\n")

A = torch.tensor([[1,2], [1,2]])
B = torch.tensor([[3,4], [3,4]])
print(A+B)
print(A-B)

tensor([ 6,  8, 10, 12])


tensor([[4, 6],
        [4, 6]])
tensor([[-2, -2],
        [-2, -2]])


In [23]:
print(A*B) # Hadamard Product
print(A/B)
print(B**2)

tensor([[3, 8],
        [3, 8]])
tensor([[0.3333, 0.5000],
        [0.3333, 0.5000]])


곱셈, 나눗셈, 제곱 > 각 성분에 대해서 해준다

- Hadamard 계산이기 때문에 동일한 shape를 가진 tensor에 적용

In [25]:
print(A@B) # element-wise 곱셈

tensor([[ 9, 12],
        [ 9, 12]])


element-wise

- (x,y)@(a,b) > y = a가 맞아야 성립

# Tensor 인덱싱

## Boolean으로 인덱싱

In [31]:
a = [1,2,3,5,4,6,3,3]
print(a==3) # 리스트 =/= 3이므로, False
print("\n")

A = torch.tensor([[1,2,3,4],[5,3,7,3]])
print(A==3) # 각 성분에 대해 해당 값과 동일한지 비교해주게 된다
print(A[A==3]) # 성분가 3과 동일한 값들로 인덱싱

False


tensor([[False, False,  True, False],
        [False,  True, False,  True]])
tensor([3, 3, 3])


In [35]:
A=torch.tensor([[1,2],[3,4],[5,6],[7,8]])
B=torch.tensor([True,False,False,True]) # 그냥 리스트여도 가능하다! tensor type 맞춰줄 필요 없다
print(A[B,:])
# 행 자리에 boolean tensor를 넣어주어 해당 boolean에 따라서 True인 행에 대해서 출력

b=torch.tensor([1,2,3,4])
print(b[[True,False,False,True]])

tensor([[1, 2],
        [7, 8]])
tensor([1, 4])


In [36]:
c=[1,2,3,4]
c[[True,False,False,True]]

TypeError: list indices must be integers or slices, not list

- tensor은 가능하지만, list는 불가능하다

## Tensor로 인덱싱

In [44]:
a=torch.tensor([1,2,3,4,5])
print(a[2])
print( a[torch.tensor(2)] ) # tensor로도 접근 가능
print()
print( a[torch.tensor([2,3,4])] )
print( a[torch.tensor([[2,2,2],[3,3,3]])] )
# 각 인덱싱에 부합하는 값으로, tensor shape에 맞춰 tensor 반환!

tensor(3)
tensor(3)

tensor([3, 4, 5])
tensor([[3, 3, 3],
        [4, 4, 4]])


In [41]:
a=torch.tensor([[1,2,3],[4,5,6]])

print( a[torch.tensor([[0,1],[1,1]])] )
# a[0] = [1,2,3] 이므로, 앞과 마찬가지로 인덱싱 값에 따라 각 위치에 맞게 tensor 반환
print( a[torch.tensor([[0,1],[1,1]])].shape )

tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[4, 5, 6],
         [4, 5, 6]]])
torch.Size([2, 2, 3])


segmentation 결과 그림 보여줄 때, tensor 인덱싱을 활용!
- 만약 고양이 그림 (5)을 주황색으로 칠한다고 하자
- 해당 5번째 인덱스를 가진 그림에 대해 3개의 값인 RGB값을 부여해야 하므로, 이때 활용한다

## 인덱싱 종류 정리

In [45]:
A = torch.Tensor([[1,2],[3,4],[5,6],[7,8]])

# 1.
print(A[0,1])
# 2.
print(A[ torch.tensor([[False,True],[False,False],[True,True],[False,True]]) ])
print(A[A==2])
# 3.
print(A[ [True,False,False,False],[False,True] ])
# 4.
print(A[ torch.tensor([1,2,2,1,2]) ])

SyntaxError: invalid syntax (4233472302.py, line 11)

In [ ]:
T