In [2]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

# n_size_ndarray_creation

함수목적
- n의 제곱수로 2 dimensional array를 생성하는 ndarray.

Args
- n: 생성하고자 하는 ndarray의 row와 column의 개수
- dtype: 생성하려는 ndarray의 data type (np.int)

Returns
- row와 column의 길이가 n인 two dimentional ndarray
- X[0,0]은 0으로 순차적으로 X[n-1,n-1]은 n^2-1이 할당됨

In [11]:
def n_size_ndarray_creation(n, dtype=np.int):
    li = []
    for i in range(n):
      for j in range(n):
        li.append( (i+1) * (j+1) -1 )
    X = np.array(li, dtype).reshape(n, n)
    return X

In [12]:
n_size_ndarray_creation(4, float)

array([[ 0.,  1.,  2.,  3.],
       [ 1.,  3.,  5.,  7.],
       [ 2.,  5.,  8., 11.],
       [ 3.,  7., 11., 15.]])

# zero_or_one_or_empty_ndarray

함수목적
- shape이 지정된 크기의 ndarray를 생성, 이때 행렬의 element는 type에 따라 0, 1 또는 empty로 생성됨.

Args
- shape: 생성할려는 ndarray의 shape
- type: 생성되는 element들의 값을 지정함0은 0, 1은 1, 99는 empty 타입으로 생성됨
- dtype: 생성하려는 ndarray의 data type (np.int)

Returns
- shape의 크기로 생성된 ndarray로 type에 따라 element의 내용이 변경됨

```
zero_or_one_or_empty_ndarray(shape=(2,2), type=1)
array([[ 1,  1],
        [ 1,  1]])
zero_or_one_or_empty_ndarray(shape=(3,3), type=99)

- 임의의수 생성

array([[1773984320,        487, 1774114944],
        [       487, 1947927088,          0],
        [1947927088,          0, 1701605485]])
```



In [13]:
def zero_or_one_or_empty_ndarray(shape, type=0, dtype=np.int):
  if type == 0:
    X = np.zeros(shape, dtype=dtype)
  elif type == 1:
    X = np.ones(shape, dtype=dtype)
  else:
    X = np.empty(shape, dtype=dtype)
  return X

In [14]:
zero_or_one_or_empty_ndarray(shape=(2,2), type=1)

array([[1, 1],
       [1, 1]])

In [15]:
zero_or_one_or_empty_ndarray(shape=(3,3), type=99)

array([[ 4151192956528754769, -5067675480698650536,  4146689356901384305],
       [-5067675480698650536,  4160889769476436884, -5070236902986717532],
       [ 4146689356901384305, -5070236902986717532,  4149419664175477595]])

# change_shape_of_ndarray

함수목적
- 입력된 ndarray X를 n_row의 값을 row의 개수로 지정한 matrix를 반환함.
- 이때 입력하는 X의 size는 2의 거듭제곱수로 전제함.
- 만약 n_row과 1일 때는 matrix가 아닌 vector로 반환함.

Args
- X: 입력하는 ndarray
- n_row: 생성할려는 matrix의 row의 개수

Returns
- row의 개수가 n_row인 Matrix 또는 Vector
- n_row가 1이면 Vector 값으로 반환함

```
>>> import numpy as np
>>> import numpy_lab as testcode
>>> X = np.ones((32,32), dtype=np.int)
>>> testcode.change_shape_of_ndarray(X, 1)
array([1, 1, 1, ..., 1, 1, 1])
>>> testcode.change_shape_of_ndarray(X, 512)
array([[1, 1],
       [1, 1],
       [1, 1],
       ...,
       [1, 1],
       [1, 1],
       [1, 1]])
```



In [28]:
def change_shape_of_ndarray(X, n_row):
    return X.reshape(n_row, -1)

In [31]:
X = np.ones((32,32), dtype=np.int)
change_shape_of_ndarray(X, 512)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


array([[1, 1],
       [1, 1],
       [1, 1],
       ...,
       [1, 1],
       [1, 1],
       [1, 1]])

In [32]:
X = np.ones((32,32), dtype=np.int)
change_shape_of_ndarray(X, 1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


array([[1, 1, 1, ..., 1, 1, 1]])

# concat_ndarray

함수목적
- 입력된 ndarray X_1과 X_2를 axis로 입력된 축을 기준으로 통합하여 반환하는 함수
- X_1과 X_2는 matrix 또는 vector 임, 그러므로 vector 일 경우도 처리할 수 가 있어야 함
- axis를 기준으로 통합할 때, 통합이 불가능하면 False가 반환됨.
- 단 X_1과 X_2 Matrix, Vector 형태로 들어왔다면, Vector를 row가 1개인 Matrix로 변환하여 통합이 가능한지 확인할 것

Args
- X_1: 입력하는 ndarray
- X_2: 입력하는 ndarray
- axis: 통합의 기준이 되는 축 0 또는 1임

Returns
- X_1과 X_2과 통합된 matrix 타입의 ndarray



```
>>> import numpy as np
>>> import numpy_lab as testcode
>>> a = np.array([[1, 2], [3, 4]])
>>> b = np.array([[5, 6]])
>>> testcode.concat_ndarray(a, b, 0)
array([[1, 2],
       [3, 4],
       [5, 6]])
>>> testcode.concat_ndarray(a, b, 1)
False
>>> a = np.array([1, 2])
>>> b = np.array([5, 6, 7])
>>> testcode.concat_ndarray(a, b, 1)
array([[1, 2, 5, 6, 7]])
>>> testcode.concat_ndarray(a, b, 0)
False
```



In [16]:
def concat_ndarray(X_1,X_2, axis=99):
  if (len(X_1.shape) == 1):
    X_1 = X_1.reshape(1, -1)

  if (len(X_2.shape) == 1):
    X_2 = X_2.reshape(1, -1)

  if axis == 1:
    if X_1.shape[0] != X_2.shape[0]:
      result = 'False'
    else:
      result = np.concatenate((X_1, X_2), axis=axis)
  else:
   if X_1.shape[1] != X_2.shape[1]:
     result = 'False'
   else:
     result = np.concatenate((X_1, X_2), axis=axis)

  return result

In [17]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

In [18]:
concat_ndarray(a, b, 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [19]:
concat_ndarray(a, b, 1)

'False'

In [20]:
a = np.array([1, 2])
b = np.array([5, 6, 7])

In [21]:
concat_ndarray(a, b, 1)

array([[1, 2, 5, 6, 7]])

In [22]:
concat_ndarray(a, b, 0)

'False'

# normalize_ndarray

함수목적
- 입력된 Matrix 또는 Vector를 ndarray X의 정규화된 값으로 변환하여 반환함
- 이때 정규화 변환 공식 Z = (X - X의평균) / X의 표준편차로 구성됨.
- X의 평균과 표준편차는 axis를 기준으로 axis 별로 산출됨.
- Matrix의 경우 axis가 0 또는 1일 경우, row 또는 column별로 Z value를 산출함.
- axis가 99일 경우 전체 값에 대한 normalize 값을 구함.

Args
- X: 입력하는 ndarray,
- axis: normalize를 구하는 기준이 되는 축으로 0, 1 또는 99임, 단 99는 axis 구분 없이 전체값으로 평균과 표준편차를 구함
- dtype: data type으로 np.float32로 구정

Returns
- 정규화된 ndarray




```
>>> import numpy as np
>>> import numpy_lab as testcode
>>> X = np.arange(12, dtype=np.float32).reshape(6,2)
>>> testcode.normalize_ndarray(X)
array([[-1.59325504, -1.3035723 ],
       [-1.01388955, -0.72420681],
       [-0.43452409, -0.14484136],
       [ 0.14484136,  0.43452409],
       [ 0.72420681,  1.01388955],
       [ 1.3035723 ,  1.59325504]], dtype=float32)
>>> testcode.normalize_ndarray(X, 1)
array([[-1.,  1.],
       [-1.,  1.],
       [-1.,  1.],
       [-1.,  1.],
       [-1.,  1.],
       [-1.,  1.]], dtype=float32)
>>> testcode.normalize_ndarray(X, 0)
array([[-1.46385002, -1.46385002],
       [-0.87831002, -0.87831002],
       [-0.29277   , -0.29277   ],
       [ 0.29277   ,  0.29277   ],
       [ 0.87831002,  0.87831002],
       [ 1.46385002,  1.46385002]], dtype=float32)
```



In [60]:
def normalize_ndarray(X, axis=99, dtype=np.float32):
  if axis == 0:
    result = (X - X.mean(axis=0)) / X.std(axis=0)
    
  elif axis == 1:
    temp_std = X.std(axis=1).reshape(-1, 1)
    temp_mean = X.mean(axis=1).reshape(-1, 1)

    for _ in range(1, X.shape[1]):
      temp_std = np.hstack((temp_std, temp_std))
      temp_mean = np.hstack((temp_mean, temp_mean))

    result = (X - temp_mean) / temp_std

  else:
    result = (X - X.mean()) / X.std()
  return result

In [61]:
X = np.arange(12, dtype=np.float32).reshape(6,2)

In [62]:
X

array([[ 0.,  1.],
       [ 2.,  3.],
       [ 4.,  5.],
       [ 6.,  7.],
       [ 8.,  9.],
       [10., 11.]], dtype=float32)

In [63]:
normalize_ndarray(X)

array([[-1.593255  , -1.3035723 ],
       [-1.0138896 , -0.7242068 ],
       [-0.4345241 , -0.14484136],
       [ 0.14484136,  0.4345241 ],
       [ 0.7242068 ,  1.0138896 ],
       [ 1.3035723 ,  1.593255  ]], dtype=float32)

In [64]:
normalize_ndarray(X, 0)

array([[-1.46385, -1.46385],
       [-0.87831, -0.87831],
       [-0.29277, -0.29277],
       [ 0.29277,  0.29277],
       [ 0.87831,  0.87831],
       [ 1.46385,  1.46385]], dtype=float32)

In [68]:
normalize_ndarray(X, 1)

array([[-1.,  1.],
       [-1.,  1.],
       [-1.,  1.],
       [-1.,  1.],
       [-1.,  1.],
       [-1.,  1.]], dtype=float32)

# save_ndarray

함수목적
- 입력된 ndarray X를 argument filename으로 저장함

Args
- X: 입력하는 ndarray
- filename: 저장할려는 파일이름



```
>>> import numpy as np
>>> import numpy_lab as testcode
>>> X = np.arange(32, dtype=np.float32).reshape(4, -1)
>>> filename = "test.npy"
>>> testcode.save_ndarray(X, filename) #test.npy 파일이 생성됨
```



In [69]:
def save_ndarray(X, filename="test.npy"):
  X.to_csv("./filename")
  pass

# boolean_index

함수목적
- 입력된 ndarray X를 String type의 condition 정보를 바탕으로 해당 컨디션에 해당하는 ndarray X의 index 번호를 반환함
- 단 이때, str type의 조건인 condition을 코드로 변환하기 위해서는 eval(str("X") + condition)를 사용할 수 있음

Args
- X: 입력하는 ndarray
- condition: string type의 조건 (">3", "== 5", "< 15")

Returns
- 조건에 만족하는 ndarray X의 index



```
>>> import numpy as np
>>> import numpy_lab as testcode
>>> X = np.arange(32, dtype=np.float32).reshape(4, -1)
>>> testcode.boolean_index(X, "== 3")
(array([0]), array([3]))
>>> X = np.arange(32, dtype=np.float32)
>>> testcode.boolean_index(X, "> 6")
(array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
        23, 24, 25, 26, 27, 28, 29, 30, 31]),)
```



In [81]:
def boolean_index(X, condition):
  result = np.where(eval(str("X") + condition))
  return result

In [83]:
X = np.arange(32, dtype=np.float32).reshape(4, -1)
X

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20., 21., 22., 23.],
       [24., 25., 26., 27., 28., 29., 30., 31.]], dtype=float32)

In [84]:
boolean_index(X, "== 3")

(array([0]), array([3]))

In [87]:
X = np.arange(32, dtype=np.float32)
X

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31.], dtype=float32)

In [86]:
boolean_index(X, "> 6")

(array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
        24, 25, 26, 27, 28, 29, 30, 31]),)

# find_nearest_value

함수목적
- 입력된 vector type의 ndarray X에서 target_value와 가장 차이가 작게나는 element를 찾아 리턴함
- 이때 X를 list로 변경하여 처리하는 것은 실패로 간주함.

Args
- X: 입력하는 vector type의 ndarray
- target_value : 가장 유사한 값의 기준값이 되는 값

Returns
- target_value와 가장 유사한 값



```
>>> import numpy as np
>>> import numpy_lab as testcode
>>> X = np.random.uniform(0, 1, 100)
>>> target_value = 0.3
>>> testcode.find_nearest_value(X, target_value)
0.29260674329282488 # 출력되는 값은 random 하게 바뀜
```



In [104]:
def find_nearest_value(X, target_value):
  best_abs = 1
  temp_ = 0

  for i in X:
    if abs(i-target_value) < best_abs:
      best_abs = abs(i-target_value)
      temp_ = i

  return temp_

In [106]:
X = np.random.uniform(0, 1, 100)
target_value = 0.3
np.sort(X)

array([0.0051183 , 0.04207864, 0.04790872, 0.05275406, 0.05358179,
       0.06075652, 0.06104157, 0.08183448, 0.0999267 , 0.10714188,
       0.11280235, 0.11365038, 0.11673542, 0.13033649, 0.13998725,
       0.15542099, 0.15967264, 0.16362194, 0.1676148 , 0.16959239,
       0.18228853, 0.18705343, 0.1990831 , 0.20659071, 0.22230542,
       0.23154455, 0.23944191, 0.24935738, 0.27216341, 0.27364136,
       0.2782441 , 0.28379265, 0.31453342, 0.31492345, 0.31671271,
       0.33394142, 0.34895971, 0.36180299, 0.36670167, 0.37540371,
       0.38650313, 0.39071081, 0.40345623, 0.41310391, 0.42335181,
       0.42669509, 0.44720368, 0.44995121, 0.45367933, 0.46589699,
       0.47197713, 0.48665814, 0.49056451, 0.49067923, 0.49828441,
       0.50665594, 0.53213824, 0.56339916, 0.56886375, 0.56993107,
       0.5720474 , 0.58613508, 0.58736988, 0.59761402, 0.61602689,
       0.62368588, 0.62562289, 0.63139195, 0.64410374, 0.68014569,
       0.6831706 , 0.69003313, 0.70103611, 0.70176935, 0.70703

In [107]:
find_nearest_value(X, target_value)

0.31453342088346736

# get_n_largest_values

함수목적
- 입력된 vector type의 ndarray X에서 큰 숫자 순서대로 n개의 값을 반환함.

Args
- X: vector type의 ndarray
- n: 반환할려는 element의 개수

Returns
- ndarray X의 element중 큰 숫자 순서대로 n개 값이 반환됨 ndarray



```
>>> import numpy as np
>>> import numpy_lab_solution as t
>>> X = np.random.uniform(0, 1, 100)
>>> t.get_n_largest_values(X, 3)
array([ 0.98935239,  0.98494578,  0.98317255])
>>> t.get_n_largest_values(X, 5)
array([ 0.98935239,  0.98494578,  0.98317255,  0.96859596,  0.96485649])
# 출력되는 값은 random 하게 바뀜
```



In [134]:
def get_n_largest_values(X, n):
    X_sort = np.sort(X)
    return X_sort[-n:]

In [122]:
X = np.random.uniform(0, 1, 100)
X

array([0.66545402, 0.80298281, 0.22703736, 0.90851551, 0.56699436,
       0.40039752, 0.03553558, 0.70533956, 0.55853852, 0.57998163,
       0.24180558, 0.98575344, 0.16841601, 0.09571313, 0.80603593,
       0.17949561, 0.70297389, 0.41160395, 0.43042107, 0.25572399,
       0.22002067, 0.02157327, 0.53326977, 0.44250658, 0.17878912,
       0.11810768, 0.96781999, 0.34625978, 0.9393807 , 0.26565785,
       0.67575352, 0.71931656, 0.10484095, 0.92275759, 0.13025304,
       0.22881903, 0.63049824, 0.37114298, 0.30168382, 0.53167019,
       0.86633153, 0.80084379, 0.54707993, 0.43037273, 0.89287324,
       0.52778397, 0.22251636, 0.13517545, 0.27107416, 0.15822815,
       0.02993042, 0.15575042, 0.28324109, 0.42819944, 0.46620369,
       0.47603741, 0.315969  , 0.80483183, 0.0877148 , 0.82479484,
       0.44258139, 0.05165001, 0.73430131, 0.31120372, 0.20972631,
       0.90730877, 0.21713415, 0.75865866, 0.3712913 , 0.78224876,
       0.22297465, 0.25824275, 0.45280794, 0.38599585, 0.64008

In [135]:
get_n_largest_values(X, 3)

array([0.96781999, 0.9856135 , 0.98575344])

In [136]:
get_n_largest_values(X, 5)

array([0.9393807 , 0.94354435, 0.96781999, 0.9856135 , 0.98575344])